name: Build and Test Plugin Template

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        java: [14]
    name: Build and Test Plugin Template
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: "adopt"
        java-version: ${{ matrix.java }}

    - name: Build and Run Tests
      run: |
          ./gradlew --info build
