name: Developer Certificate of Origin Check

on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: DCO Check
        uses: tisonkun/actions-dco@v1.1
